### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by ACPK** [cloocher/aggcat#18]
I get TypeError: no implicit conversion of Symbol into Integer for the following code:

    client = Aggcat.scope(24)
    response = client.discover_and_add_accounts(14007, 'akelley', 'password')

**Comment by bendangelo** [comment]
This happens when your X.509 Public Certificate expires. Need to create a new one here https://developer.intuit.com/docs/0020_customeraccountdata/009_using_customeraccountdata/0010_gettingstarted/0015_create_an_cad_integration/0033_create_x.509_keys
