### ISSUE TITLE
`refresh=true` on `update_login` isn't working

### ISSUE THREAD

**Issue by hrrf** [cloocher/aggcat#21]
I think I'd expect an http response with a list of all accounts at the institution that was updated.  Right now, even with `?refresh=true` (https://github.com/cloocher/aggcat/blob/master/lib/aggcat/client.rb#L63) hard-coded in the params, I just get a 200 and nothing else.  Am I doing something wrong?

**Comment by cloocher** [comment]
@hrrf,

Have you tried using API Explorer (https://developer.intuit.com/apiexplorer)?  Do you see different results there?

**Comment by hrrf** [comment]
The API Explorer appears to be down.  It hasn't worked for a while, I don't
think.

On Tue, Feb 3, 2015 at 10:12 PM, Gene Drabkin <notifications@github.com>
wrote:

> @hrrf <https://github.com/hrrf>,
>
> Have you tried using API Explorer (
> https://developer.intuit.com/apiexplorer)? Do you see different results
> there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloocher/aggcat/issues/21#issuecomment-72791930>.
>



-- 
-=n

**Comment by hrrf** [comment]
Disregard, perhaps my setup is incomplete.

On Tue, Feb 3, 2015 at 10:31 PM, Nathan Lamb <nathan.lamb@gmail.com> wrote:

> The API Explorer appears to be down.  It hasn't worked for a while, I
> don't think.
>
> On Tue, Feb 3, 2015 at 10:12 PM, Gene Drabkin <notifications@github.com>
> wrote:
>
>> @hrrf <https://github.com/hrrf>,
>>
>> Have you tried using API Explorer (
>> https://developer.intuit.com/apiexplorer)? Do you see different results
>> there?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cloocher/aggcat/issues/21#issuecomment-72791930>.
>>
>
>
>
> --
> -=n
>



-- 
-=n

**Comment by hrrf** [comment]
NO - I can't get the CAD API explorer to work, in any event.

On Tue, Feb 3, 2015 at 10:38 PM, Nathan Lamb <nathan.lamb@gmail.com> wrote:

> Disregard, perhaps my setup is incomplete.
>
> On Tue, Feb 3, 2015 at 10:31 PM, Nathan Lamb <nathan.lamb@gmail.com>
> wrote:
>
>> The API Explorer appears to be down.  It hasn't worked for a while, I
>> don't think.
>>
>> On Tue, Feb 3, 2015 at 10:12 PM, Gene Drabkin <notifications@github.com>
>> wrote:
>>
>>> @hrrf <https://github.com/hrrf>,
>>>
>>> Have you tried using API Explorer (
>>> https://developer.intuit.com/apiexplorer)? Do you see different results
>>> there?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/cloocher/aggcat/issues/21#issuecomment-72791930>.
>>>
>>
>>
>>
>> --
>> -=n
>>
>
>
>
> --
> -=n
>



-- 
-=n

**Comment by cloocher** [comment]
@hrrf - any updates?
