### ISSUE TITLE
Downloading Institution list

### ISSUE THREAD

**Issue by ACPK** [cloocher/aggcat#24]
What is the recommended way to download the list of institutions from Intuit? Due to the large nature of the list, I'm guessing that I should use pagination (see [Intuit's API docs](https://developer.intuit.com/docs/0100_accounting/0300_developer_guides/querying_data#/Pagination)) but does this gem support it?

**Comment by cloocher** [comment]
@ACPK,

Institutions list changes very infrequently.  You can fetch the list, say, once a week and store a copy of it somewhere on your side.
